language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t zukowskmichal/docker-react -f Dockerfile.dev ./flow_react_app/frontend/

script:
  - docker run -e CI=true zukowskimichal/docker-react npm run test
