os: linux
dist: xenial
language: generic

services:
  - docker

before_install:
  - docker build -t zukowskimichal/docker-react -f PATH/frontend/Dockerfile.dev

script:
  - docker run -e CI=true zukowskimichal/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-316472426292"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
