os: linux
dist: xenial
language: generic

services:
  - docker

before_install:
  - docker build -t zukowskimichal/docker-test -f ./complex/client/Dockerfile.dev ./complex/client

script:
  - docker run -e CI=true zukowskimichal/docker-test npm run test
#after tests execute sucessfully
after_sucess:
  - docker build -t zukowskimichal/complex-nginx -f ./complex/nginx ./complex/nginx
  - docker build -t zukowskimichal/complex-server -f ./complex/server ./complex/server
  - docker build -t zukowskimichal/complex-client -f ./complex/client ./complex/client
  - docker build -t zukowskimichal/complex-worker -f ./complex/worker ./complex/worker

#log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#push images to dockerhub : D
  - docker push zukowskimichal/complex-nginx
  - docker push zukowskimichal/complex-server
  - docker push zukowskimichal/complex-client
  - docker push zukowskimichal/complex-worker


# deploy:
#   provider: elasticbeanstalk
#   region: "eu-central-1"
#   app: "docker-react"
#   env: "DockerReact-env"
#   bucket_name: "elasticbeanstalk-eu-central-1-316472426292"
#   bucket_path: "docker-react"
#   on:
#     branch: main
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
